webos-compat.inc: re-blacklist omxplayer
ros/meta-ros-webos pull request #13
Opened 2021-05-03 14:02 UTC by shr-project

* meta-webosose blacklists it already:
  meta-webos-raspberrypi/conf/machine/include/webos-rpi.inc:PNBLACKLIST[omxplayer] ?= "not compatible with webOS Open components"
  meta-webos-raspberrypi/conf/machine/include/webos-rpi.inc:PNBLACKLIST[packagegroup-rpi-test] ?= "rdepends on omxplayer"
  meta-webos/conf/distro/include/webos-recipe-blacklist.inc:PNBLACKLIST[omxplayer] ?= "ERROR: omxplayer-git-r4 do_compile: Function failed: do_compile: DllAvFormat.h:117:51: error: ::avio_feof has not been declared"

* but meta-ros-common has different conditional blacklist:
  meta-ros-common/conf/ros-distro/include/ros-world-recipe-blacklist.inc:PNBLACKLIST[omxplayer] ?= "${@bb.utils.contains('ROS_WORLD_SKIP_GROUPS', 'world-license', 'depends on libav, libomxil which has a restricted license not whitelisted in LICENSE_FLAGS_WHITELIST', '', d)}"

  now when PNBLACKLISTs were removed here in webos-compat.inc (which is
  included from meta-ros-webos/conf/layer.conf), the ros-world-recipe-blacklist.inc
  is parsed first, so the conditional is respected, but then in webOS OSE builds
  it conflicts with libavutil and libswresample:

ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libavformat.so.58: libavformat, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/bin/omxplayer.bin)
ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libavutil.so.56: libavutil, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/lib/omxplayer/libavfilter.so.7.16.100)
ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libavutil.so.56: libavutil, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/bin/omxplayer.bin)
ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libswscale.so.5: libswscale, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/bin/omxplayer.bin)
ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libavutil.so.56: libavutil, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/lib/omxplayer/libavcodec.so.58.18.100)
ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libavcodec.so.58: libavcodec, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/lib/omxplayer/libavformat.so.58.12.100)
ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libswresample.so.3: libswresample, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/lib/omxplayer/libavcodec.so.58.18.100)
ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libavutil.so.56: libavutil, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/lib/omxplayer/libswscale.so.5.1.100)
ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libavutil.so.56: libavutil, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/lib/omxplayer/libavformat.so.58.12.100)
ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libavcodec.so.58: libavcodec, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/bin/omxplayer.bin)
ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libavutil.so.56: libavutil, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/lib/omxplayer/libavdevice.so.58.3.100)
ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libswresample.so.3: libswresample, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/bin/omxplayer.bin)
ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libavformat.so.58: libavformat, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/lib/omxplayer/libavdevice.so.58.3.100)
ERROR: omxplayer-git-r5 do_package: omxplayer: Multiple shlib providers for libavutil.so.56: libavutil, omxplayer (used by files: /jenkins/home/workspace/jansa/webos-melodic-hardknott/webos-melodic-hardknott/tmp-glibc/work/raspberrypi4-webos-linux-gnueabi/omxplayer/git-r5/packages-split/omxplayer/usr/lib/omxplayer/libswresample.so.3.1.100)

Signed-off-by: Martin Jansa <martin.jansa@lge.com>

2021-05-03 18:53 UTC, herb-kuta-lge requested changes

2021-05-03 18:53 UTC, herb-kuta-lge commented on conf/ros-distro/include/webos-compat.inc
> +# meta-raspberrypi/recipes-multimedia/omxplayer/omxplayer_git.bb:do_compile
Add comment so as to match the others above it:
```
# meta-webos/conf/distro/include/webos-recipe-blacklist.inc:PNBLACKLIST[omxplayer] ?= "ERROR: omxplayer-git-r4 do_compile: Function failed: do_compile: DllAvFormat.h:117:51: error: ::avio_feof has not been declared"
```

2021-05-03 21:40 UTC, herb-kuta-lge approved these changes

2021-05-13 11:09 UTC, merged

2021-05-13 11:12 UTC, shr-project commented
Merged to other branches as well:
   67cbe89..26b63df  dunfell -> dunfell-next
   67cbe89..b48a2c5  gatesgarth -> gatesgarth
   67cbe89..b48a2c5  gatesgarth -> gatesgarth-next
   67cbe89..b48a2c5  hardknott -> hardknott
   67cbe89..b48a2c5  hardknott -> hardknott-next
   67cbe89..b48a2c5  master -> master
   67cbe89..b48a2c5  master -> master-next